import client from 'lib/axios'

/**
 * Get a single token (Ghost or onchain). There's 2 ways to get it:
 * 1) Pass to API value, onchainValue, and marketID as input
 * 2) Pass to API listingID as input
 * @param value -- the canonical URL (not a token name from old market)
 * @param onchainValue -- the value that is stored on chain (URL for URL market, @name for twitter market, etc)
 * @param marketID -- id of market this token is being listed on. ID determined by data returned from subgraph
 * @param listingId -- id generated by web2 for this listing
 */
export const getSingleListing = async ({
  value,
  onchainValue,
  marketId,
  listingId,
  jwt,
}) => {
  const decodedValue = decodeURIComponent(value) // Decode so that special characters look normal
  try {
    const params = listingId
      ? {
          listingId,
        }
      : {
          value: decodedValue,
          onchainValue,
          marketId,
        }

    const response = await client.get(`/listing/single`, {
      params,
      headers: {
        Authorization: jwt ? `Bearer ${jwt}` : null,
      },
    })

    return response?.data?.data?.listing
  } catch (error) {
    console.error('Could not get this single listing', error)
  }
}
